language: r

matrix:
  include:
    - os: linux
      dist: release
    - os: linux
      dist: devel
    - os: osx
      dist: oldrel
    - os: osx
      dist: release

# Copied from broom
sudo: required
cache: packages
bioc_required: false
warnings_are_errors: false

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"


r_binary_packages:
  - rstanarm
  - rstan
